name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Steve'
      home:
        description: 'location'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
        echo "mvn clean package"
        # This step checks out a copy of your repository.
        - uses: actions/checkout@v2
        # This step references the directory that contains the action.
        - uses: ./.github/workflows/
